using System;
using System.Collections.Generic;
using MonoGameLibrary;

namespace BloodScroll;

//
// HOW ONE LAYER PLAYS
//
// Built from a formula that scales with the layer index and the chosen difficulty,
// then whatever mobWaves.json says for this layer is merged over the top.
//

public class WaveData
{
    // LAYER DATA
    public int LayerIndex { get; set; }
    public LayerType LayerType { get; set; }

    // WAVE DATA
    public int? WavesToBeat { get; set; }

    // GIFTS THAT THE PLAYER GETS WHEN BEATING A LEVEL
    public GiftData Gifts { get; set; }

    // HOW MANY OF EACH MOB SPAWN PER WAVE
    public Dictionary<MobType, int> Mobs { get; set; } = [];

    // WAVE TIMER
    public float? WavesTimerSeconds { get; set; }
    public float? WavesTimer { get; set; }

    // Bosses generated by BossSchedule get tougher every time the roster comes around
    public float HpScale { get; set; } = 1f;

    // Parameterless constructor for the JSON deserializer
    public WaveData() {}

    public WaveData(int layerIndex)
    {
        LayerIndex = layerIndex;
        LayerType = LayerType.Normal;

        // Waves timer seconds je enako kot st waves to beat (se veča slightly, da imaš malo več časa)
        WavesTimerSeconds = (LayerIndex / 5) + 3;
        WavesTimer = 0.0f;

        SetDifficulty();
    }

    // THE ONE PLACE A MOB COUNT IS ASKED FOR, so it is the one place the caps
    // have to hold. Enforcing them in SetDifficulty alone would let a number
    // written by hand in mobWaves.json walk straight past them, and the whole
    // point of a cap is that there is no way round it.
    public int MobCount(MobType type)
    {
        int wanted = Mobs.TryGetValue(type, out int n) ? n : 0;

        return Cap.TryGetValue(type, out int most) ? Math.Min(wanted, most) : wanted;
    }

    //
    // HOW MANY OF A THING IS TOO MANY
    //
    // A TYPE MISSING FROM THIS TABLE HAS NO LIMIT - that is what the bats are:
    // the swarm, meant to pile up forever.
    //
    // Everything else is capped, and the layer gets harder above the cap by
    // sending more bats instead. The green spider has the tightest cap.
    private static readonly Dictionary<MobType, int> Cap = new()
    {
        [MobType.Jellyfish] = 5,
        [MobType.Spider] = 2,
        [MobType.GreenSpider] = 1,
        [MobType.Butterfly] = 2,
    };

    // The two late mobs, and the layer each starts turning up on. Both are
    // things the player has to already understand something else to read: the
    // green bat only means anything once ordinary bats are routine, and the
    // green spider only reads as different once a normal web is familiar.
    private const int GREEN_BAT_FROM_LAYER = 6;
    private const int GREEN_SPIDER_FROM_LAYER = 10;

    //
    // HOW MANY OF EVERYTHING THIS LAYER SENDS
    //
    // Every count here is the MEDIUM curve. Difficulty.Count bends it twice for
    // baby and hell: one fewer/more to start, and a slower/faster climb.
    //
    public void SetDifficulty()
    {
        // Začnemo z base = 2, base+1 vsak wave do boss-a, po vsakem bossu je base++
            // 0 = 2 bats per wave
            // 1 = 3 bats per wave
            // 2 = 4 bats per wave
            // 3 = 5 bats per wave
            // 4 = boss level, tam se vse nastavi ročno
            // 5 = 3 bats per wave
            // ...
        //
        // Two halves: one step per boss cycle cleared, a smaller one per pair of
        // layers inside the current cycle.
        int swarmProgress = (LayerIndex / 5) + (LayerIndex % 5) / 2;

        int swarm = Difficulty.Count(2, swarmProgress, cap: 8);

        Mobs[MobType.Bat] = swarm;

        // Rode the swarm curve and drowned the screen. Capped now (see Cap) -
        // the layer gets harder with more bats, not with more floating walls.
        Mobs[MobType.Jellyfish] = swarm;

        // Same curve but starting from 0 instead of 2
        Mobs[MobType.PurpleBat] = Difficulty.Count(0, swarmProgress, cap: 8);

        // THE POISON BAT. One or two in a wave, never a swarm of its own: the
        // poison does not stack usefully and a screen full of green would just
        // be a permanent debuff rather than a hit the player can react to.
        Mobs[MobType.GreenBat] = LayerIndex < GREEN_BAT_FROM_LAYER
            ? 0
            : Difficulty.Count(1, (LayerIndex - GREEN_BAT_FROM_LAYER) / 8, cap: 3);

        // THE TWO GROUND MOBS. They take the floor away as somewhere safe to
        // stand. The crab only exists on the ground layer (see MobManager) and
        // that layer is written by hand, so this is the slime's curve.
        Mobs[MobType.Slime] = Difficulty.Count(0, LayerIndex / 5, cap: 3);
        Mobs[MobType.Crab] = Difficulty.Count(0, LayerIndex / 5, cap: 3);

        // Flowers are placed on platforms when the layer is built, so this is the
        // count for the WHOLE layer, not per wave. Capped so a layer never runs
        // out of clean ledges.
        //
        // THE DIFFICULTY DOES NOT TOUCH THIS ONE - a flower is a bomb the player
        // keeps, so hell would end up with the most ammunition lying about.
        Mobs[MobType.Flower] = Math.Min(3 + LayerIndex / 6, 7);

        // Ceiling spiders join once the player has found his feet
        Mobs[MobType.Spider] = LayerIndex < 3
            ? 0
            : Difficulty.Count(1, LayerIndex / 12, cap: 2);

        // THE GREEN ONE. Late, and never more than one - it nails the
        // player to the spot rather than slowing him. Baby holds the first one
        // back a full ten layers: not weakened, just met later.
        Mobs[MobType.GreenSpider] = LayerIndex < GREEN_SPIDER_FROM_LAYER
            ? 0
            : Difficulty.Count(1, (LayerIndex - GREEN_SPIDER_FROM_LAYER) / 10, cap: 1);

        // One butterfly a wave - the only healing there is outside a boss kill,
        // and the same one wherever the difficulty is set. Taking the heal away
        // on hell would not make it harder, it would make it shorter.
        Mobs[MobType.Butterfly] = LayerIndex < 2 ? 0 : 1;

        // Začnemo z dvema wave-oma, po vsakem bossu + 1 wave
            // 0...7  = 2 waves
            // 8...15 = 3 waves
            // 16...  = 4 waves
        // Never below two, whatever baby's slower climb works out to. Never above
        // eight, because every wave's bats are BUILT when the layer is - see
        // MobManager.GenerateAllSleepingMobs.
        WavesToBeat = Math.Clamp(Difficulty.Count(2, LayerIndex / 8), 2, 8);
    }

    // Merges the hand authored settings for this layer over the generated ones.
    // Anything the JSON does not mention keeps its generated value.
    public void MergeFrom(WaveData data)
    {
        if (data == null)
            return;

        LayerIndex = data.LayerIndex;
        LayerType = data.LayerType;
        WavesToBeat = data.WavesToBeat ?? WavesToBeat;
        WavesTimerSeconds = data.WavesTimerSeconds ?? WavesTimerSeconds;
        HpScale = data.HpScale;

        if (data.Gifts != null)
        {
            Gifts ??= new GiftData();
            Gifts.MergeFrom(data.Gifts);
        }

        //
        // A BOSS LAYER IS ONLY ITS BOSS AND WHAT IT WAS GIVEN TO FIGHT ALONGSIDE
        //
        // THE ONE PLACE THE SWARM IS SILENCED, and it has to be here. What is
        // being merged INTO is a WaveData built moments ago by MobManager, and
        // its constructor has already run the whole normal curve - bats,
        // jellyfish, slimes, the lot. A roster cleared on the way in gets
        // merged on TOP of that and silences nothing, which is how boss layers
        // ended up carrying a full swarm on top of the boss.
        //
        // Every count the roster does not mention therefore has to be wiped,
        // not overwritten - a boss fight is exactly what it says it is.
        //
        if (LayerType == LayerType.Boss)
            Mobs.Clear();

        // Per mob: a count named by the roster or the JSON replaces whatever
        // was generated for this layer
        foreach (var (type, count) in data.Mobs)
            Mobs[type] = count;

        // A BOSS LAYER IS ALWAYS ONE WAVE, whatever was written for it - the
        // boss arrives with the wave and the layer ends when it drops (see
        // Layer.LayerFinished). A second wave would send in a second boss.
        if (LayerType == LayerType.Boss)
            WavesToBeat = 1;
    }
}
