using System;
using System.Collections.Generic;
using MonoGameLibrary;

namespace BloodScroll;

//
// HOW ONE LAYER PLAYS
//
// Built from a formula that scales with the layer index and the chosen difficulty,
// then whatever mobWaves.json says for this layer is merged over the top.
//

public class WaveData
{
    // LAYER DATA
    public int LayerIndex { get; set; }
    public LayerType LayerType { get; set; }

    // WAVE DATA
    public int? WavesToBeat { get; set; }

    // GIFTS THAT THE PLAYER GETS WHEN BEATING A LEVEL
    public GiftData Gifts { get; set; }

    // HOW MANY OF EACH MOB SPAWN PER WAVE
    public Dictionary<MobType, int> Mobs { get; set; } = [];

    // WAVE TIMER
    public float? WavesTimerSeconds { get; set; }
    public float? WavesTimer { get; set; }

    // Bosses generated by BossSchedule get tougher every time the roster comes around
    public float HpScale { get; set; } = 1f;

    // Parameterless constructor for the JSON deserializer
    public WaveData() {}

    public WaveData(int layerIndex)
    {
        LayerIndex = layerIndex;
        LayerType = LayerType.Normal;

        // Waves timer seconds je enako kot st waves to beat (se veča slightly, da imaš malo več časa)
        WavesTimerSeconds = (LayerIndex / 5) + 3;
        WavesTimer = 0.0f;

        SetDifficulty();
    }

    // THE ONE PLACE A MOB COUNT IS ASKED FOR, so it is the one place the caps
    // have to hold. Enforcing them in SetDifficulty alone would let a number
    // written by hand in mobWaves.json walk straight past them, and the whole
    // point of a cap is that there is no way round it.
    public int MobCount(MobType type)
    {
        int wanted = Mobs.TryGetValue(type, out int n) ? n : 0;

        return Cap.TryGetValue(type, out int most) ? Math.Min(wanted, most) : wanted;
    }

    //
    // HOW MANY OF A THING IS TOO MANY
    //
    // Bats are the swarm. They are meant to pile up without limit - that is the
    // shape of the whole game and outrunning them is the skill it teaches.
    //
    // The rest are NOT swarm mobs, and they stop being interesting long before
    // they stop multiplying:
    //   a jellyfish is a slow floating hazard you route around. Fifteen of them
    //   is not fifteen decisions, it is a wall.
    //   a spider is a web every couple of seconds. Enough spiders and the
    //   player is simply held in place while the bats arrive, which is not a
    //   fight, it is a cutscene.
    //   a butterfly is a heal. More than a couple and the healing stops being
    //   something worth crossing a room for.
    //
    // So they are capped, and the layer gets harder above the cap by sending
    // more bats instead.
    //
    // A TYPE MISSING FROM THIS TABLE HAS NO LIMIT, which is what the bats are
    // for. The black spider has the tightest cap of all - losing the controls
    // is the harshest thing the game does, and it only stays frightening while
    // it stays rare.
    private static readonly Dictionary<MobType, int> Cap = new()
    {
        [MobType.Jellyfish] = 5,
        [MobType.Spider] = 3,
        [MobType.BlackSpider] = 2,
        [MobType.Butterfly] = 2,
    };

    // The two late mobs, and the layer each starts turning up on. Both are
    // things the player has to already understand something else to read: the
    // green bat only means anything once ordinary bats are routine, and the
    // black spider only reads as different once a normal web is familiar.
    private const int GREEN_BAT_FROM_LAYER = 6;
    private const int BLACK_SPIDER_FROM_LAYER = 10;

    //
    // HOW MANY OF EVERYTHING THIS LAYER SENDS
    //
    // Every count here is the MEDIUM curve; Difficulty.Count is what bends it
    // for baby and hell, and it bends it twice - one fewer or one more to start
    // with, and a slower or faster climb from there. See Difficulty.
    //
    public void SetDifficulty()
    {
        // Začnemo z base = 2, base+1 vsak wave do boss-a, po vsakem bossu je base++
            // 0 = 2 bats per wave
            // 1 = 3 bats per wave
            // 2 = 4 bats per wave
            // 3 = 5 bats per wave
            // 4 = boss level, tam se vse nastavi ročno
            // 5 = 3 bats per wave
            // ...
        //
        // The two halves of the swarm's growth: one step for every boss cycle
        // the player has cleared, and a smaller one for each pair of layers
        // inside the cycle he is on.
        int swarmProgress = (LayerIndex / 5) + (LayerIndex % 5) / 2;

        int swarm = Difficulty.Count(2, swarmProgress, cap: 8);

        Mobs[MobType.Bat] = swarm;

        // Rode the swarm curve and drowned the screen. Capped now (see Cap) -
        // the layer gets harder with more bats, not with more floating walls.
        Mobs[MobType.Jellyfish] = swarm;

        // Same curve but starting from 0 instead of 2
        Mobs[MobType.PurpleBat] = Difficulty.Count(0, swarmProgress, cap: 8);

        // THE POISON BAT. One or two in a wave, never a swarm of its own: the
        // poison does not stack usefully and a screen full of green would just
        // be a permanent debuff rather than a hit the player can react to.
        Mobs[MobType.GreenBat] = LayerIndex < GREEN_BAT_FROM_LAYER
            ? 0
            : Difficulty.Count(1, (LayerIndex - GREEN_BAT_FROM_LAYER) / 8, cap: 3);

        // THE TWO GROUND MOBS. Neither is a threat on its own - what they do is
        // take the floor away as somewhere safe to stand while the bats work on
        // you. They used to be a flat difficulty count, which meant the easiest
        // setting never saw one at all; they now creep in with the climb like
        // everything else, so meeting one is something the run earns.
        //
        // The crab only ever exists on the ground layer (see MobManager) and
        // that layer's count is written by hand, so this is the slime's curve
        // in practice.
        Mobs[MobType.Slime] = Difficulty.Count(0, LayerIndex / 5, cap: 3);
        Mobs[MobType.Crab] = Difficulty.Count(0, LayerIndex / 5, cap: 3);

        // Flowers are placed on platforms when the layer is built, so this is
        // how many hide on the WHOLE layer, not how many per wave. Enough of
        // them that a climb has to be picked around rather than walked up, and
        // enough that there is usually one in reach when a bomb is wanted.
        // Capped so a layer never runs out of clean ledges to land on.
        //
        // THE DIFFICULTY DOES NOT TOUCH THIS ONE. A flower is a bomb the player
        // gets to keep, so handing hell mode more of them than baby - which is
        // what tying it to the setting did - made the hardest setting the one
        // with the most ammunition lying about.
        Mobs[MobType.Flower] = Math.Min(3 + LayerIndex / 6, 7);

        // Ceiling spiders join once the player has found his feet
        Mobs[MobType.Spider] = LayerIndex < 3
            ? 0
            : Difficulty.Count(1, LayerIndex / 8, cap: 3);

        // THE BLACK ONE. Late, and never more than a couple - it does not slow
        // the player down, it nails him to the spot, and that is only
        // frightening while it is rare. On baby that first one is held back a
        // full ten layers, which is the difficulty doing exactly what it should
        // with a mob this harsh: not weakening it, just meeting it later.
        Mobs[MobType.BlackSpider] = LayerIndex < BLACK_SPIDER_FROM_LAYER
            ? 0
            : Difficulty.Count(1, (LayerIndex - BLACK_SPIDER_FROM_LAYER) / 10, cap: 2);

        // One butterfly a wave - the only healing there is outside a boss kill,
        // and the same one wherever the difficulty is set. Taking the heal away
        // on hell would not make it harder, it would make it shorter.
        Mobs[MobType.Butterfly] = LayerIndex < 2 ? 0 : 1;

        // Začnemo z dvema wave-oma, po vsakem bossu + 1 wave
            // 0...7  = 2 waves
            // 8...15 = 3 waves
            // 16...  = 4 waves
        // Never below two, whatever baby mode's slower climb works out to: one
        // wave is not a layer, it is a corridor with a bat in it. And never
        // above eight, because every wave's worth of bats is BUILT when the
        // layer is (see MobManager.GenerateAllSleepingMobs) - past that the
        // layer stops being a longer fight and starts being a longer wait.
        WavesToBeat = Math.Clamp(Difficulty.Count(2, LayerIndex / 8), 2, 8);
    }

    // Merges the hand authored settings for this layer over the generated ones.
    // Anything the JSON does not mention keeps its generated value.
    public void MergeFrom(WaveData data)
    {
        if (data == null)
            return;

        LayerIndex = data.LayerIndex;
        LayerType = data.LayerType;
        WavesToBeat = data.WavesToBeat ?? WavesToBeat;
        WavesTimerSeconds = data.WavesTimerSeconds ?? WavesTimerSeconds;
        HpScale = data.HpScale;

        if (data.Gifts != null)
        {
            Gifts ??= new GiftData();
            Gifts.MergeFrom(data.Gifts);
        }

        // Per mob: a count written in the JSON replaces the generated one,
        // so a boss layer can silence the normal swarm with "Bat": 0
        foreach (var (type, count) in data.Mobs)
            Mobs[type] = count;

        // A BOSS LAYER IS ALWAYS ONE WAVE, whatever was written for it. The
        // boss walks in with the wave and the layer is over when it drops
        // (see Layer.LayerFinished) - a second wave would send in a second
        // boss, and a difficulty setting that quietly did that on some layers
        // and not others is not a difficulty setting, it is a bug.
        if (LayerType == LayerType.Boss)
            WavesToBeat = 1;
    }
}
